global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "task-manager"
    metrics_path: /metrics
    static_configs:
      - targets: ["task-manager:8080"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
