global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "milvus"
    metrics_path: /metrics
    static_configs:
      - targets: ["milvus:9091"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
